# Copyright (C) 2018 Sur Herrera Paredes

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PATRICDATA = '/home/sur/micropopgen/exp/2018/today3/patric'
OUTDIR = '/home/sur/micropopgen/exp/2018/today3/data_for_roary'
BINDIR = '/home/sur/micropopgen/src/micropopgen/patric'

rule all:
    input:
        OUTDIR + "/preprocess/Streptococcus_anginosus/1000570.3/1000570.3.gff",
        OUTDIR + "/preprocess/Streptococcus_anginosus/1000570.8/1000570.8.gff"
        OUTDIR + "/preprocess/Streptococcus_anginosus/1000570.3/1000570.3.fna",
        OUTDIR + "/preprocess/Streptococcus_anginosus/1000570.8/1000570.8.fna"

rule preprocess_patric_gff:
    input:
        PATRICDATA + "/{species}/{id}/{id}.PATRIC.gff"
    output:
        OUTDIR + "/preprocess/{species}/{id}/{id}.gff"
    shell:
        # "perl -e 'while(<>){{chomp; "
        # "my ($chr, $pat, $type, $start, $end, $point, "
        # "$strand, $num, $annot) = split(/\t/, $_); "
        # "$chr =~ s/^accn\|//; my ($id, @trash) = split(/;/, $annot); "
        # "$id =~ s/^ID=fig\|//; print join(\"\t\", ($chr, $pat, $type, "
        # "$start, $end, $point, $strand, $num, $id)) . \"\n\"}}' "
        # "{input} > {output}"
        BINDIR + '/patric2roary_gff.py --infile {input} --outfile {output}'

rule preprocess_patric_fna:
    input:
        PATRICDATA + "/{species}/{id}/{id}.fna"
    output:
        OUTDIR + "/preprocess/{species}/{id}/{id}.fna"
    shell:
        BINDIR + '/fasta_remove_desc.py --infile {input} --outfile {output}'
