# Copyright (C) 2018 Sur Herrera Paredes

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PATRICDATA = '/home/sur/micropopgen/exp/2018/today3/patric'
OUTDIR = '/home/sur/micropopgen/exp/2018/today3/roary'
BINDIR = '/home/sur/micropopgen/src/micropopgen/patric'
# specs = ['Streptococcus_anginosus', 'Streptococcus_anginosus']
# ids = ['1000570.3', '1000570.8']

rule all:
    input:
        # expand(OUTDIR + "/roary_input/{file}", file=config['files'])
        expand(OUTDIR + "/roary_input/{species}-{id}.gff", zip,
               species=config['species'],
               id=config['ids'])

rule preprocess_patric_gff:
    input:
        # PATRICDATA + "/{species}/{id}/{id}.PATRIC.gff"
        expand(PATRICDATA + "/{species}/{id}/{id}.PATRIC.gff", zip,
               species=config['species'],
               id=config['ids'])
    output:
        # temp(OUTDIR + "/preprocess/{species}/{id}/{id}.gff")
        temp(expand(OUTDIR + "/preprocess/{species}/{id}/{id}.gff", zip,
                    species=config['species'],
                    id=config['ids']))
    shell:
        BINDIR + '/patric2roary_gff.py --infile {input} --outfile {output}'

rule preprocess_patric_fna:
    input:
        # PATRICDATA + "/{species}/{id}/{id}.fna"
        expand(PATRICDATA + "/{species}/{id}/{id}.fna", zip,
               species=config['species'],
               id=config['ids'])
    output:
        # temp(OUTDIR + "/preprocess/{species}/{id}/{id}.fna")
        temp(expand(OUTDIR + "/preprocess/{species}/{id}/{id}.fna", zip,
                    species=config['species'],
                    id=config['ids']))
    shell:
        BINDIR + '/fasta_remove_desc.py --infile {input} --outfile {output}'

rule create_patric_gff:
    input:
        expand(OUTDIR + "/preprocess/{species}/{id}/{id}.gff", zip,
               species=config['species'],
               id=config['ids']),
        expand(OUTDIR + "/preprocess/{species}/{id}/{id}.fna", zip,
               species=config['species'],
               id=config['ids'])
    output:
        expand(OUTDIR + "/roary_input/{species}-{id}.gff", zip,
               species=config['species'],
               id=config['ids'])
    shell:
        "cat {input} > {output}"
